### ISSUE TITLE
How to upgrade from rke 0.14.1 

### ISSUE THREAD

**Issue by herrbpl** [rancher/terraform-provider-rke#184]
How to upgrade if previous state information in terraform state is for provider rke 0.14.1 and it contains deprecated fields like services_etcd.

Currently rke provider 1.0.0-rc4 seems to get panic
```
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:
Error: rpc error: code = Canceled desc = context canceled


panic: runtime error: invalid memory address or nil pointer dereference
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a2b56e]
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: goroutine 30 [running]:
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/rke.flattenRKEClusterServicesEtcdBackupConfig(0xc0001529c0, 0xc000754e00, 0x0, 0x0, 0x398e860, 0x1, 0xc0008333e0)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/rke/structure_rke_cluster_services_etcd.go:59 +0x4e
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/rke.flattenRKEClusterServicesEtcd(0xc0002dd590, 0x24, 0xc000152990, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/rke/structure_rke_cluster_services_etcd.go:95 +0x9f6
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/rke.flattenRKEClusterServices(0xc0002dd590, 0x24, 0xc000152990, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/rke/structure_rke_cluster_services.go:21 +0xe3    
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/rke.flattenRKECluster(0xc00043c620, 0xc00001a000, 0x0, 0x0)    
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/rke/structure_rke_cluster.go:123 +0xa14
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/rke.resourceRKEClusterRead(0xc00043c620, 0x1c4db00, 0xc0003c3e90, 0xc00043c620, 0x0)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/rke/resource_rke_cluster.go:99 +0x14a
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005e9400, 0xc0000a8b90, 0x1c4db00, 0xc0003c3e90, 0xc00085a870, 0xc0000a8b90, 0x0)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000eb48, 0x244efe0, 0xc0006e23f0, 0xc0000a8820, 0xc00000eb48, 0xc0006e23f0, 0xc0006e0bd0)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d7
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1e31280, 0xc00000eb48, 0x244efe0, 0xc0006e23f0, 0xc0004b6300, 0x0, 0x244efe0, 0xc0006e23f0, 0xc00096c000, 0x2f0d5)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ae160, 0x2471b40, 0xc000108f00, 0xc000604400, 0xc000024420, 0x3959010, 0x0, 0x0, 0x0)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc/server.go:995 +0x4662020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0002ae160, 0x2471b40, 0xc000108f00, 0xc000604400, 0x0)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005e6140, 0xc0002ae160, 0x2471b40, 0xc000108f00, 0xc000604400)
2020-03-20T12:19:18.996Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc/server.go:710 +0x9f 
2020-03-20T12:19:18.997Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4: created by github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-03-20T12:19:18.997Z [DEBUG] plugin.terraform-provider-rke_v1.0.0-rc4:      /go/src/github.com/rancher/terraform-provider-rke/vendor/google.golang.org/grpc/server.go:708 +0xa1 
2020-03-20T12:19:19.000Z [DEBUG] plugin: plugin process exited: path=/root/.terraform.d/plugins/terraform-provider-rke_v1.0.0-rc4 pid=9675 error="exit status 2"
```
Terraform version: 0.12.17  
Go runtime version: go1.12.13
name -r: 4.9.184-linuxkit

**Comment by rawmind0** [comment]
Panic fixed on PR #185 . Deprecated arguments are detailed on  [CHAGELOG.md](https://github.com/rancher/terraform-provider-rke/blob/master/CHANGELOG.md#100-rc1-january-21-2020)

**Comment by iahmad-khan** [comment]
Hi, I am running 0.14.1 and I am just wondering when to upgrade? is there a major release soon? or do i need to go step by step through rc versions? thanks

**Comment by rawmind0** [comment]
@iahmad-khan , due to we are promoting the provider to be officially supported by hashicorp, from v0.14.1 the provider has been hugely refactored. We are releasing rc versions in the meanwhile the provider is officially supported.

On last rc, v1.0.0-rc5, we've added new features (as resource import) and support for RKE v1.1.0 . There is a bunch of deprecated arguments from v0.14.1, please take a look [CHANGELOG.md](https://github.com/rancher/terraform-provider-rke/blob/master/CHANGELOG.md#100-rc1-january-21-2020)

**Comment by iahmad-khan** [comment]
Hi, I see that. Shall I wait for next major release or just keep updating?

**Comment by AMoghrabi** [comment]
Hey @rawmind0 we are just getting started with RKE terraform. Similar to what @iahmad-khan has asked, should I be using v1.0.0-rc5 or should I stick with v0.14.1?

I've tried 0.14.1 and it's a little difficult to use as the examples in the repo don't exactly follow what the provider provides.

Thanks!

**Comment by rawmind0** [comment]
As mentioned, `v1.0.0-rcX` versions implements huge provider refactor (including docs) and support for recent versions of RKE. 

To clarify that, today we've cut first major provider release, [v1.0.0](https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.0)

**Comment by mwei0210** [comment]
Tried using the newer version v1.0.0, the bootstrap time has increased significantly compare to 0.14, is it expected or is there anything we could do to fasten the process?

**Comment by rawmind0** [comment]
Another option to upgrade is to import the rke cluster on new provider version. 

* Save `rke_cluster_yaml` and `rke_state` arguments as `cluster.yml` and `cluster.rkestate` files
* Define tf file, see above
* Execute the import, `terraform import rke_cluster.foo  cluster.yml:cluster.rkestate`

tf file
```
resource rke_cluster "cluster" {
  cluster_yaml = file("cluster.yml")
}
```

Once rke cluster is imported, it can be managed by cluster_yaml and/or by provider arguments (if both defined arguments take precedence)

Please, reopen issue if needed
